### ISSUE TITLE
Farmer and Tools

### ISSUE THREAD

**Issue by DropDaBassTC** [TangoTek/What-If-Villager-Community#102]
**Describe the bug**
Farmer not seeing proper tools.  Sheep have not been sheered, but every time they feed an animal, they show a need for sheers, but there are 3 in the storage.

**To Reproduce**
Not entirely sure how to replicate it, just watch the farmer.

**Expected behavior**
Expect him to milk the cows and sheer sheer
(Milk occasionally happens but yet to get any wool.)

**Screenshots**
![2019-04-11_10 47 58](https://user-images.githubusercontent.com/49350174/55980445-57633c00-5c49-11e9-9b08-add7d3b89594.png)

** Logs **
If possible, send your latest.log file in your /logs folder.

**Comment by TheGreatNaj** [comment]
Ive been super confused by this because my first rancher NEVER picked up the shears I made for him from storage but the second one did. Wont pick up replacements though after the shears broke.

**Comment by MakaniValur** [comment]
<img width="848" alt="Screenshot 2019-04-15 at 14 51 36" src="https://user-images.githubusercontent.com/49378993/56138403-c238ae00-5f8e-11e9-9335-c6af9068ed51.png">

Same problem. He doesn't want the bucket at his feet, he doesn't want bucket in storage but he just desperately wants a bucket... I should add that he's also just standing in storage waiting/hoping for one to show up in his inventory, rather than working...

**Comment by TangoTek** [comment]
Fixed. AI Ordering issue
