### ISSUE TITLE
Idea for villager happiness

### ISSUE THREAD

**Issue by OhTheNoises** [TangoTek/What-If-Villager-Community#107]
Would it be plausible that if the player does actions like hoeing land that has been flagged for hoeing, taking wood to the blacksmith for charcoal and putting it in the furnace, putting potatoes in the furnace, etc could increase happiness. 

Essentially when a player does a villager's job, they get happy (short of the actual harvesting of things)

It might be a way to involve the player more.

**Comment by TangoTek** [comment]
I love the idea of getting the player more engaged, but there really isn't a way for me to know when the player is doing a villager's job.  Maybe in the case of chopping a tree the player could predict the individual tree the lumberjack was going to, but that seems really hard.

Also, I'm torn.  On one hand I definitely want the player to be involved in their village more instead of just spectating.  However, I dont want to encourage the player to make some of the professions obsolete.  

I think the player need something more to do, but I dont think its doing the villagers job for them.  But I've been wrong before (OK many times)

Btw, great suggestion!
