### ISSUE TITLE
Minors fortune diamonds with a wooden pick

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#37]
My minor has a default wooden pick, and I put two diamond ore in the mineshaft. Miner came up with 3 diamonds in his inventory.

**Comment by TangoTek** [comment]
As designed currently.  It has nothing to do with Fortune per say, but Miners can harvest more ore/gems than they naturally should.  This is because I thought they were going to be getting far few resources per time spent mining.  I want miners to adequately supply the blacksmith and be a solid contributor to the economy.   Right now every gem/ore has a skill/100 chance of being duplicated.  So a level 100 miner will double all ore/gems gathered.

Also, unlike vanilla, the pick material doesn't currently factor into what can be harvested
