### ISSUE TITLE
Miner holds on to items

### ISSUE THREAD

**Issue by MakaniValur** [TangoTek/What-If-Villager-Community#46]
So I've had this happen a few times now - my miner has loads of ore in her inventory, walks all the way back up to storage, grabs something (in this case two potatoes) but doesn't drop any of her ore off while she's there, instead taking it back down into the mine with her..

**Comment by LiteHorizon** [comment]
also having this issue.

**Comment by TangoTek** [comment]
Miners only drop off items at the end of the day (around dusk).  This is to reduce trips to the storage room since the trip is usually very long.

There is also a small chance that deliver tasks just might be skipped due to randomization.  I think I will priority these type of tasks when the villager is already in the storage room.
